ton-org/blueprint

src/utils.ts
Fixes https://github.com/ton-community/blueprint/issues/9
=> Disable choice menu when there is a single file

src/network/createNetworkProvider.ts
Fixes https://github.com/ton-community/blueprint/issues/19
=> Convert bounce error to warning

.github/workflow/publish.yml, README.md, example/README.md, package.json
- updated package name
- added auto-deploy to NPM
- updated readme links
=> Ton org migration

src/cli/cli.ts, src/cli/help.ts, src/network/NetworkProvider.ts, src/network/createNetworkProvider.ts, src/network/send/MnemonicProvider.ts, yarn.lock
Your Grace,
With utmost reverence and deepest respect, I humbly beseech your gracious attention to a matter of great import. In the realm of code and innovation, a humble Pull Request hath been submitted within the sacred halls of GitHub. This contribution, meticulously crafted and nurtured, seeks your benevolent approval to merge into the noble repository.
I entreat you to spare a moment from your exalted duties to cast your discerning gaze upon this humble plea. The code therein, a product of ceaseless toil and tireless dedication, has been fashioned to enhance the quality and prowess of our digital domain. Its harmonious integration shall bestow upon us the boon of progress.
As the sun bows to the horizon and the quill dances upon parchment, I implore you, sire, to grant your noble …
=> Custom endpoint (new)

CHANGELOG.md, package.json, src/templates/tact/counter/contracts/contract.tact.template, yarn.lock
=> chore: update tact

src/cli/verify.ts
So, the verifier registry address [has been changed](https://github.com/ton-blockchain/verifier/commit/1b74a43dbad5bbe0f1919ed25ffb2e0abb5efcb2) under funny enough commit named `remove console.log`.
In order to address this issue, verifier registry address is now obtained through the source registry contract, which is core to the verification system and unlikely to change.
=> Source registry instead of hardcoded verifier registry

CHANGELOG.md, README.md, package.json, src/cli/constants.ts, src/cli/create.ts, src/compile/CompilerConfig.ts, src/compile/compile.ts, src/index.ts, src/templates/tolk/common/compilables/compile.ts.template, src/templates/tolk/counter/contracts/contract.tolk.template, src/templates/tolk/counter/scripts/deploy.ts.template, src/templates/tolk/counter/scripts/increment.ts.template, src/templates/tolk/counter/tests/spec.ts.template, src/templates/tolk/counter/wrappers/wrapper.ts.template, src/templates/tolk/empty/contracts/contract.tolk.template, src/templates/tolk/empty/scripts/deploy.ts.template, src/templates/tolk/empty/tests/spec.ts.template, src/templates/tolk/empty/wrappers/wrapper.ts.template, src/templates/tolk/not-separated-common/wrappers/compile.ts.template, yarn.lock
**Tolk** is a new language for writing smart contracts in TON. Think of Tolk as the "next‑generation FunC".
Tolk compiler is literally a fork of FunC compiler, introducing familiar syntax similar to TypeScript,
but leaving all low-level optimizations untouched.
**[The PR into ton-blockchain repo](https://github.com/ton-blockchain/ton/pull/1345)**
* the user is able to create contracts in three languages: FunC, Tolk, Tact (both from UI and command-line)
* templates 'empty' and 'counter', like for FunC and Tact
* contracts are compiled with [tolk-js](https://github.com/ton-blockchain/tolk-js), a WASM wrapper, like func-js
* no file like 'stdlib.fc' exists, because stdlib is embedded into Tolk distribution
To dig into Tolk and how it differs from FunC, read the …
=> Support for Tolk Language: next-generation FunC

README.md
=> Add `blueprint-misti` to the list of plugins

CHANGELOG.md, package.json, src/templates/tact/counter/contracts/contract.tact.template, src/templates/tact/counter/scripts/deploy.ts.template, src/templates/tact/counter/scripts/increment.ts.template, src/templates/tact/counter/tests/spec.ts.template, src/templates/tact/empty/contracts/contract.tact.template, src/templates/tact/empty/scripts/deploy.ts.template, src/templates/tact/empty/tests/spec.ts.template, yarn.lock
=> chore: update Tact templates and bump Tact version

src/compile/compile.ts
=> fix(compile): fix Tact compilation check

CHANGELOG.md, src/build.ts, src/compile/compile.ts, src/index.ts
=> feature: add function to build all tact contracts

CHANGELOG.md, src/build.ts, src/compile/compile.ts
=> feat: show compiler version when building contracts

CHANGELOG.md, src/cli/create.ts, src/utils/index.ts, src/utils/string.utils.ts
=> feat: make error for invalid contract name nicer

CHANGELOG.md, src/templates/tact/counter/scripts/deploy.ts.template
=> fix: fix tact counter deploy script template

CHANGELOG.md, package.json, src/utils/selection.utils.ts
=> fix: fix build command in tact projects

src/templates/tact/counter/scripts/deploy.ts.template, src/templates/tact/counter/scripts/increment.ts.template, src/templates/tact/empty/scripts/deploy.ts.template
=> fix: fix tact scripts templates to support wrappers from build dir

CHANGELOG.md, README.md, src/cli/Runner.ts, src/cli/cli.ts, src/cli/constants.ts, src/cli/create.ts, src/cli/rename.spec.ts, src/cli/rename.ts, src/utils/string.utils.ts
=> feat: add possibility to rename contracts 

CHANGELOG.md, README.md, src/network/Network.ts, src/network/createNetworkProvider.ts, src/network/send/MnemonicProvider.ts
=> feat: add subwallet id settings in .env

CHANGELOG.md, README.md, src/network/Network.ts, src/network/createNetworkProvider.ts, src/network/send/DeeplinkProvider.ts, src/network/send/MnemonicProvider.ts, src/network/send/TonConnectProvider.ts, src/utils/ton.utils.ts
Closes #67
Should be merged after #216
=> fix: fix testnet address formatting

CHANGELOG.md, src/templates/func/common/contracts/imports/stdlib.fc.template, src/templates/func/not-separated-common/contracts/imports/stdlib.fc.template
=> feat: update stdlib

CHANGELOG.md, src/compile/compile.ts, src/index.ts
=> feature: export getCompilerConfigForContract function

CHANGELOG.md, package.json, src/templates/tolk/counter/contracts/contract.tolk.template
=> feature: add tolk v0.13 support

.github/workflows/qa.yaml
=> run test and build on matrix os

CHANGELOG.md, package.json, src/templates/tolk/counter/contracts/contract.tolk.template
=> fix: fix tolk counter template

CHANGELOG.md, src/index.ts, src/network/NetworkProvider.ts, src/network/createNetworkProvider.ts, src/utils/ton.utils.ts
Closes #224, closes #32, closes #162
=> feat: add possibility to wait for transaction

README.md
Closes #310
Please ensure the following items are completed before requesting review:
=> chore: fix language typo in readme 

src/network/Explorer.ts, src/network/NetworkProvider.ts, src/network/createNetworkProvider.ts, src/utils/ton.utils.ts
Closes #<issue-number>
Please ensure the following items are completed before requesting review:
=> feat: add `explorer` method to network provider

src/templates/tolk/empty/contracts/contract.tolk.template
Closes #316
Please ensure the following items are completed before requesting review:
=> fix: use modern `onInternalMessage` entry point signature

CHANGELOG.md, src/cli/create.ts, src/cli/rename.ts, src/utils/string.utils.ts
Closes #314
Please ensure the following items are completed before requesting review:
=> feat: add retry for contract name input
